$init_script = <<-'SCRIPT'
sudo apt-get update -y
sudo apt-get install -y debconf-utils vim curl wget openjdk-8-jdk lsb-release unzip gnupg --allow-insecure-repositories
export DEBIAN_FRONTEND="noninteractive";
sudo debconf-set-selections <<< 'mysql-apt-config mysql-apt-config/select-server select mysql-8.0'
wget https://dev.mysql.com/get/mysql-apt-config_0.8.14-1_all.deb
sudo -E dpkg -i mysql-apt-config_0.8.14-1_all.deb
sudo apt-get update
echo "Installing MySQL 8..."
sudo debconf-set-selections <<< 'mysql-community-server mysql-community-server/re-root-pass password root'
sudo debconf-set-selections <<< 'myvsql-community-server mysql-community-server/root-pass password root'
sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
sudo -E apt-get -y install mysql-server --allow-unauthenticated
echo "INSTALL JAVA..."
sudo apt -y install openjdk-8-jdk
java -version
echo "INSTALL GRADLE..."
wget -c https://services.gradle.org/distributions/gradle-6.7.1-bin.zip -P /tmp
sudo unzip -d /opt/gradle /tmp/gradle-6.7.1-bin.zip
echo 'export GRADLE_HOME=/opt/gradle/gradle-6.7.1' >> ~/.bashrc
echo 'export PATH=${GRADLE_HOME}/bin:${PATH}' >> ~/.bashrc
gradle --version
mysql -u root -p"root" -e "CREATE DATABASE e4l;"
# Update the root user password
mysql -u root -p"root" -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '12345678';"
sudo su
export GRADLE_HOME=/opt/gradle/gradle-6.7.1
export PATH=${GRADLE_HOME}/bin:${PATH}
echo "INSTALL NPM..."
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
# Ensure NVM is available in non-interactive shell
echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.profile
echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm' >> ~/.profile
echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion' >> ~/.profile
echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.bashrc
echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm' >> ~/.bashrc
echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion' >> ~/.bashrc
perl -i -p0e 's/# If not running interactively,[^#]*//se' ~/.bashrc
# Apply changes to the current shell session
source ~/.bashrc
nvm install v15.14.0
nvm alias default v15.14.0
nvm use default
cp ~/.bashrc /home/vagrant/.bashrc
cp -r ~/.nvm /home/vagrant/.nvm
cp ~/.profile /home/vagrant/.profile
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDFiEpj6Jf530QnpjEtECcQ0uMWGv/Okbb1VilWTUd9R5Ng+5S4DJcLjojgrQ0mBphWfSbC8hlHzPsZBsB4/EqaV0xcRq7jBwG+gjopxS5WGqUAoAQmtb1bUOSLHWeSIuYhb9jl39awauHeqzAFmxEZFuILOOw+uM97I5l6Q5DFQriXsj++jc0ofnPRYdrSU6/It6bqt5UcR4Qa3Eruee7cLl3G9K/Cd+hsZTZHEkpSnQQwoRFhRxU45nDE5RNG0Qi3uqnN0gVJs+JuEX/h16/pczmdvqwDgSXVhG+xVs6AkuceCZInUKkyQzT4h1izZGGxNr7AcCye389DPzSpa6BTlw3Pc+I1pzFEx/CVnTCtpSKdtQ79WaTqMZhWPk1F8wAl4RZCEeKsvtPkU6kQEGjo9A1B1tjY3qZtx6vSqeHibWDLTTDeqcWjXA+gYwNzLI9JllADYSq4ijeyLbl4fvBc7nK1I126Exe+qUgFBpDoZywa+47SiAfO3f1VIOzIvks+njfwx8O8jnyq/uACC4LJ77hX3P02SXNuw1T6jbqYbuvFpIAudFI8k8H8CVPDk/MMY6xLlqeQWCJcxNkkD/8pwdYr0NawFn/D5veTGIxT4NT6RPjyQdTVGtjKiqk2/ZrQSxiE7JfE3lrbfoCbNQEBJfVMAFv8FGAFO9rEEr4NTQ== vagrant@integration-server" >> /home/vagrant/.ssh/authorized_keys
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDFiEpj6Jf530QnpjEtECcQ0uMWGv/Okbb1VilWTUd9R5Ng+5S4DJcLjojgrQ0mBphWfSbC8hlHzPsZBsB4/EqaV0xcRq7jBwG+gjopxS5WGqUAoAQmtb1bUOSLHWeSIuYhb9jl39awauHeqzAFmxEZFuILOOw+uM97I5l6Q5DFQriXsj++jc0ofnPRYdrSU6/It6bqt5UcR4Qa3Eruee7cLl3G9K/Cd+hsZTZHEkpSnQQwoRFhRxU45nDE5RNG0Qi3uqnN0gVJs+JuEX/h16/pczmdvqwDgSXVhG+xVs6AkuceCZInUKkyQzT4h1izZGGxNr7AcCye389DPzSpa6BTlw3Pc+I1pzFEx/CVnTCtpSKdtQ79WaTqMZhWPk1F8wAl4RZCEeKsvtPkU6kQEGjo9A1B1tjY3qZtx6vSqeHibWDLTTDeqcWjXA+gYwNzLI9JllADYSq4ijeyLbl4fvBc7nK1I126Exe+qUgFBpDoZywa+47SiAfO3f1VIOzIvks+njfwx8O8jnyq/uACC4LJ77hX3P02SXNuw1T6jbqYbuvFpIAudFI8k8H8CVPDk/MMY6xLlqeQWCJcxNkkD/8pwdYr0NawFn/D5veTGIxT4NT6RPjyQdTVGtjKiqk2/ZrQSxiE7JfE3lrbfoCbNQEBJfVMAFv8FGAFO9rEEr4NTQ== vagrant@integration-server" >> /home/vagrant/.ssh/id_rsa.pub
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "integration-server"

  config.vm.define "production",  primary: true do |production|
        production.vm.network "forwarded_port", guest: 8080, host: 8080
        production.vm.network "forwarded_port", guest: 8081, host: 8081
        production.vm.network "private_network", ip: "192.168.60.3"
        production.vm.provision "shell", inline: $init_script , run: 'always'
  end

  config.vm.define  "gitlab" do |gitlab|
        gitlab.vm.network "private_network", ip: "192.168.60.2"
        gitlab.vm.provision "ansible" do |ansible|
                ansible.playbook = "./playbook/playbook.yml"
        end
        gitlab.vm.provision "shell", inline: <<-SHELL
                sudo apt-get update
                sudo apt-get install --yes python
                apt-get install -y apache2
                SHELL
  end


  ENV['LC_ALL']="C.UTF-8"
  config.vm.provider "virtualbox" do |vb|
        vb.customize [ "modifyvm", :id, "--uart1", "off" ]
        vb.customize [ "modifyvm", :id, "--uart2", "off" ]
        vb.customize [ "modifyvm", :id, "--uart3", "off" ]
        vb.customize [ "modifyvm", :id, "--uart4", "off" ]
        vb.memory = "8182"
        vb.cpus = 4
  end
  config.vm.synced_folder ".","/vagrant", disabled: true
end
