# vim: ts=2
---
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
    
  
  vars:
    vHome: /home/vagrant
  tasks:
    - include_role:
        name: gitlab

    - include_role:
        name: nmap

    - include_role:
        name: docker

    - name: Copy admin_token.sh to the remote host
      ansible.builtin.copy:
          src: roles/shell/tasks/admin_token.sh
          dest: /home/vagrant/admin_token.sh
    - name: Copy .gitlab-ci.yml in the right repository
      ansible.builtin.copy:
          src: roles/shell/tasks/.gitlab-ci.yml
          dest: /home/vagrant/.gitlab-ci.yml

    - include_role:
        name: shell

