---
image : maven
stages:
 - build
 - test
 - run
 - upload
 - deploy

cache:
 paths:
   - target/

build_app:
 stage: build
 script:
   - mvn compile

test_app:
 stage: test
 script:
   - mvn test

run_app:
 stage: run
 script:
   - mvn package
   - mvn exec:java -Dexec.mainClass="com.jcg.maven.App"


upload_app:
    stage: upload
    tags:
    - integration
    script:
    - echo "Deploy review app"
    artifacts:
        name: "my-app"
        paths:
        - target/*.jar

deploy:
    stage: deploy
    tags:
    - stage-vm-shell
    script:
    - cp target/*.jar /home/vagrant/stage
