image: bluecode23/devops_dockerfile-app:latest

before_script:
  - apt-get update -qq && apt-get install -y curl

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev/build
    - lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev/nodes_modules

build_app:
  stage: build
  tags:
    - integration
  script:
    # TODO: add the correct directory before running gradle
    - gradle clean
    - gradle build
    # TODO: add the correct directory before running npm
    - npm install
    - npm rebuild node-sass
    - mkdir -p node_modules/node-sass/vendor

test_app:
  stage: test
  tags:
    - integration
  script:
    - bash gradle_test_java.sh

deploy_app:
  stage: deploy
  tags:
    - integration
  script:
    - echo "$(pwd)"
    - gradle bootRun &
    - npm start

deploy to production:
  stage: deploy
  script: make deploy
  environment:
    name: production
    url: http://192.168.60.2/gitlab/root/project.git
