image: ubuntu:22.04
before_script:
    - apt-get update -qq && apt-get install -y curl
stages:
  - build
  - test
  - deploy

cache:
  paths:
    - lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev/build
    - lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev/nodes_modules

build_app:
  stage: build
  tags:
    - integration
  script:
    # TODO: add the correct directory
    - gradle clean
    - gradle build
    # TODO: add the correct directory
    - npm i package
    - npm rebuild node-sass
    - mkdir node_modules/node-sass/vendor

test_app:
  stage: test
  tags:
    - integration
  script:
    - bash gradle_test_java.sh

deploy_app:
  stage: deploy
  tags:
    - integration
  script:
    - echo "$(pwd)"
    - gradle bootRun &
    - npm start
