image: ubuntu:22.04
stages:
  - build
  - test
  - deploy

cache:
  paths:
    - lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev/build
    - lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev/nodes_modules

build_app:
  stage: build
  tags:
    - integration
  script:
    - bash scripts/frontend_script.sh
    - bash scripts/backend_script.sh

test_app:
  stage: test
  tags:
    - integration
  script:
    - bash gradle_test_java.sh

deploy_app:
  stage: deploy
  tags:
    - integration
  script:
    - echo "$(pwd)"
    - gradle bootRun &
    - npm start
