image: bluecode23/devops_dockerfile-app:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev/build
    - lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev/node_modules

build_app:
  stage: build
  tags:
    - integration
  script:
    - cd lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev
    - mkdir -p /builds/gitlab/root/project/lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev/node_modules
    - cp -r /node_modules/* /builds/gitlab/root/project/lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev/node_modules
    - chmod +x gradlew || echo "Failed to make gradlew executable"
    - ./gradlew clean --info
    - ./gradlew build --refresh-dependencies


test_app:
  stage: test
  tags:
    - integration
  script:
    - cd lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev
    - chmod +x gradlew || echo "Failed to make gradlew executable"
    - ./gradlew test --info || echo "Gradlew test failed"
  artifacts:
    when: always # This ensures that the reports are saved even if the job fails
    reports:
      junit: build/test-results/test/




deploy_app:
  stage: deploy
  tags:
    - integration
  script:
    - cd lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev
    - chmod +x gradlew || echo "Failed to make gradlew executable"
    - ./gradlew clean --info
    - ./gradlew build --refresh-dependencies
    - ./gradlew bootRun --no-daemon || echo "Gradlew bootRun failed"