image: bluecode23/devops_dockerfile-app:latest

before_script:
  - apt-get update -qq && apt-get install -y curl

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev/build
    - lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev/node_modules

build_app:
  stage: build
  tags:
    - integration
  script:
    - cd lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev
    - ls -la # Debug: List files to ensure gradlew is present and permissions are correct
    - chmod +x gradlew || echo "Failed to make gradlew executable"
    - ./gradlew clean --info
    - ./gradlew build --refresh-dependencies
    - npm install
    - npm rebuild node-sass
    - mkdir -p node_modules/node-sass/vendor

test_app:
  stage: test
  tags:
    - integration
  script:
    - cd lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev
    - chmod +x gradlew || echo "Failed to make gradlew executable"
    - ./gradlew test --info || echo "Gradlew test failed"

deploy_app:
  stage: deploy
  tags:
    - integration
  script:
    - cd lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev
    - chmod +x gradlew || echo "Failed to make gradlew executable"
    - ./gradlew bootRun --no-daemon || echo "Gradlew bootRun failed"
    - cd lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev # Replace with your actual path to the npm project
    - npm start || echo "NPM start failed"