image: bluecode23/devops_dockerfile-app:latest

before_script:
  - apt-get update -qq && apt-get install -y curl

stages:
  - build
  - test
  - deploy
  - release

cache:
  paths:
    - lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev/build
    - lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev/node_modules

build_app:
  stage: build
  tags:
    - integration
  script:
    - cd lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev
    - ls -la # Debug: List files to ensure gradlew is present and permissions are correct
    - chmod +x gradlew || echo "Failed to make gradlew executable"
    - ./gradlew clean --info
    - ./gradlew build --refresh-dependencies
    - npm install
    - npm rebuild node-sass
    - mkdir -p node_modules/node-sass/vendor


unit_test:
  stage: test
  tags:
    - integration
  script:
    - cd lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev
    - chmod +x gradlew || echo "Failed to make gradlew executable"
    - ./gradlew :test --tests "lu.uni.e4l.platform.service.UnitTest.testIsNumber"


integration_test:
  stage: test
  tags:
    - integration
  script:
    - echo "TODO"


acceptance_test:
  stage: test
  tags:
    - integration
  script:
    - echo "TODO"




deploy_app:
  stage: deploy
  tags:
    - integration
  script:
    - chmod 600 .ssh/id_rsa
    - sed -i "s\\#API_URL=http://localhost:8080/e4lapi\API_URL=http://localhost:8080/e4lapi\g" lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev/.env
    - sed -i "s\API_URL=http://192.168.33.94:8080/e4lapi\\#API_URL=http://192.168.33.94:8080/e4lapi\g" lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev/.env  
    - scp -o StrictHostKeyChecking=no -o ForwardAgent=no -i .ssh/id_rsa -r *  vagrant@192.168.60.3:/home/vagrant
    - ssh -o StrictHostKeyChecking=no -o ForwardAgent=no -i .ssh/id_rsa vagrant@192.168.60.3 "cd /home/vagrant/lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev; nohup gradle bootRun > backend.log 2>&1 </dev/null &"
    - sleep 12s
    - ssh -o StrictHostKeyChecking=no -o ForwardAgent=no -i .ssh/id_rsa vagrant@192.168.60.3 "cd /home/vagrant/lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev; npm i package;npm rebuild node-sass"
    - ssh -o StrictHostKeyChecking=no -o ForwardAgent=no -i .ssh/id_rsa vagrant@192.168.60.3 "cd /home/vagrant/lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev; npm start > frontend.log 2>&1 </dev/null &"

Release:
  stage: release
  tags:
    - integration
  when: manual
  script:
    - chmod 600 .ssh/id_rsa
    - sed -i "s\\#API_URL=http://localhost:8080/e4lapi\API_URL=http://localhost:8080/e4lapi\g" lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev/.env
    - sed -i "s\API_URL=http://192.168.33.94:8080/e4lapi\\#API_URL=http://192.168.33.94:8080/e4lapi\g" lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev/.env
    - scp -o StrictHostKeyChecking=no -o ForwardAgent=no -i .ssh/id_rsa -r *  vagrant@192.168.60.3:/home/vagrant
    - ssh -o StrictHostKeyChecking=no -o ForwardAgent=no -i .ssh/id_rsa vagrant@192.168.60.3 "cd /home/vagrant/lu.uni.e4l.platform.api.dev/lu.uni.e4l.platform.api.dev; nohup gradle bootRun > backend.log 2>&1 </dev/null &"
    - sleep 12s
    - ssh -o StrictHostKeyChecking=no -o ForwardAgent=no -i .ssh/id_rsa vagrant@192.168.60.3 "cd /home/vagrant/lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev; npm i package;npm rebuild node-sass"
    - ssh -o StrictHostKeyChecking=no -o ForwardAgent=no -i .ssh/id_rsa vagrant@192.168.60.3 "cd /home/vagrant/lu.uni.e4l.platform.frontend.dev/lu.uni.e4l.platform.frontend.dev; npm start > frontend.log 2>&1 </dev/null &"