---

- name: Edit gitlab config 1
  become: true
  shell: >
    sed -i "s\external_url 'http://gitlab.example.com'\external_url 'http://192.168.60.2/gitlab'\g" /etc/gitlab/gitlab.rb
- name: Edit gitlab config 2
  become: true
  shell: sed -i 's/# unicorn\['\''port'\''\] = 8080/unicorn\['\''port'\''\] = 8088/' /etc/gitlab/gitlab.rb
- name: Edit gitlab config 3
  become: true
  shell: >
    sed -i 's/# gitlab_rails\['\''initial_root_password'\''\] = "password"/gitlab_rails['\''initial_root_password'\''\] = "aaaaaaaa"/g' /etc/gitlab/gitlab.rb
- name: Restart gitlab 1
  become: true
  shell: sudo gitlab-ctl reconfigure
- name: Restart gitlab 2
  become: true
  shell: sudo gitlab-ctl restart unicorn
- name: Restart gitlab 3
  become: true
  shell: sudo gitlab-ctl restart
- name: Create docker username
  shell: |
    usermod -aG docker vagrant
- name: Generate accesstoken
  become: true
  shell: |
    sudo bash admin_token.sh > outputofadmin
- name: Generate the repository on github
  shell: |
    curl  --request POST --header "PRIVATE-TOKEN: $(find  -type f -name 'admin-access-token.txt' -exec cat {} \;)" --header "Content-Type: application/json" --data '{"name": "project"}' --url "http://192.168.60.2/gitlab/api/v4/projects/"
- name: Clone the repo
  shell: |
    git clone https://github.com/BlueCode23/DevOPs.git
- name: Create the repository 1
  become: true
  shell: |
    mkdir project
- name: Create the repository 2
  become: true
  shell: |
    rsync -a  DevOPs/ project/
- name: Create the repository 3
  become: true
  shell: |    
    mv .gitlab-ci.yml project/.gitlab-ci.yml
- name: Create the repository 4
  become: true
  shell: |
    cd project
    rm -rf .git
    rm -rf .github
- name: Create the repository 5
  become: true
  shell: |
    git init
- name: Create the repository 6
  become: true
  shell: |
    git config --global credential.helper store
    echo "http://root:aaaaaaaa@192.168.60.2" > ~/.git-credentials
    echo "bin" >> .gitignore
- name: Create the repository 7
  become: true
  shell: |
    git remote add origin http://192.168.60.2/gitlab/root/project.git
- name: Create the repository 8
  become: true
  shell: |
    pwd
    git add .
- name: Create the repository 9
  become: true
  shell: |
    git config --global user.name "vagrant"
    git config --global user.email "admin@example.com"
- name: Create the repository 10
  become: true
  shell: |
    git commit -m "inital commit"
- name: Create the repository 11
  become: true
  shell: |
    git push -u origin master

- name: Install gitrunner
  become: true
  shell: |
    curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
    apt-get install gitlab-runner

- name: Get the runners token
  become: true
  shell: sudo gitlab-rails runner -e production "puts Gitlab::CurrentSettings.current_application_settings.runners_registration_token" > runner_token
- name: create the runner
  become: true
  shell: |
     sudo gitlab-runner register --non-interactive --url "http://192.168.60.2/gitlab" -r "$(cat runner_token)" --description "docker" --tag-list "integration" --executor "docker" --docker-image "alpine:latest" --run-untagged="true"
